### ISSUE TITLE
Allow to specify notfication type per chat ID

### ISSUE THREAD

**Issue by gsantner** [devnull-tools/jenkins-notifier#10]
As suggested in #9 allow multiple notifcation type, this issue is about
allowing to specify a notification type per (telegram)-chat-id.

eg:  -23151:sb,-12341:b    (still broken, broken)

And general options below the input, to apply general rules / defaults if nothing is choosen.

Some like of "Add new entry", which adds a new line for chat id, and check marks is also possible.
-> Like Project settings -> Source-Code-Management -> Git -> Repositories

**Comment by ataxexe** [comment]
Again, sorry for the delay. It's a good idea and fits nice with your previous issue. I'm currently working on it to implement in a simple way for all notification channels.

Thanks!!

**Comment by ataxexe** [comment]
I'm thinking about a simple set of input texts, one for each build status, plus a global one (for all status). This will keep things simple and provide room for future improvements.

**Comment by gsantner** [comment]
No problem! Good suggestion!

**Comment by ataxexe** [comment]
Done! Thanks a lot for contributing.
