### ISSUE TITLE
No UI after install

### ISSUE THREAD

**Issue by lifeguardmedia** [devnull-tools/jenkins-notifier#4]
Hi,
we've built the hpi file and installed it on our jenkins ci. We can see that the plugin is installed in "Manage Plugins" and in the log and jenkins was restarted but we cannot use the plugin.
There are no settings for jenkins-notifier in "manage jenkins" and no post-build step we can add to a build. 
What could be the problem? Our jenkins is running on java7 and we tried building the hpi with java 7 and java 8

**Comment by ataxexe** [comment]
Sorry for the delay, the log messages shows anything related to this?
