### ISSUE TITLE
Help: How to get Telegram chatId

### ISSUE THREAD

**Issue by andhie** [devnull-tools/jenkins-notifier#5]
It is unclear on how to get chatId so it can be input into the post-build config.
as i checked other bot tutorials, they wrote codes to get chatId.

**Comment by ataxexe** [comment]
You can get the chatId with a simple process:

1- Send a message to the bot or the group that has your bot
2- Check for updates using the [Telegram Bot API][getUpdates]
3- Grab the "chat" object of the returned JSON, this object will have an id, that's the id you should put in the plugin

IDs for users are positive and for groups chats are negatives. The ID will be the same for any bot you have, so you don't need to grab the ID again if you're using another bot to send the messages.

I hope it helps

[getUpdates]: https://core.telegram.org/bots/api#getupdates
