### ISSUE TITLE
Multiple Telegram Chat-IDs

### ISSUE THREAD

**Issue by gsantner** [devnull-tools/jenkins-notifier#8]
Hi there,
are multiple Chat-Ids for Telegram Notifcations supported?
Something like `id1|id2|id3` or `id1,id2,id3` would be great.

**Comment by ataxexe** [comment]
Currently I does not support it, but I think this is a nice one to have. I'll see what I can do.

Thank you!

**Comment by gsantner** [comment]
Thanks for responding so fast, and implementing this!
May I add two additional suggestions?

**Comment by ataxexe** [comment]
Of course! Just open another issues if your suggestions are not related to this one.

**Comment by gsantner** [comment]
Added issue no 9 & 10
