### ISSUE TITLE
Allow different types of notifications

### ISSUE THREAD

**Issue by gsantner** [devnull-tools/jenkins-notifier#9]
Allow different types of notifications: 
* Broken (first one, never deliver if its broken and broken again, reset when successful)
* Still Broken (broken, broken, ..)
* Successful (first one, never deliver if successful again, reset when broken)
* Successful when it was broken before (to get to know if a recent update fixed it :) )

**Comment by ataxexe** [comment]
Sorry for the delayed response. This is a nice feature and I'll work on it for sure.

I'm just thinking about notifying successful builds if the last one is also successful, if the last one is broken, then the type will be something like "fixed". There is a flag for notifying successful builds so, if it's not desirable being notified when a build is successful, just uncheck the flag.

Makes sense?

**Comment by gsantner** [comment]
Makes totally sense! 👍
